#!/bin/sh

tmux_init()
{
    tmux new-session -s work -d
    tmux split-window -d -p 50 -t work:1 -h
    tmux split-window -d -p 30 -t work:1.2 -v

    tmux -2 attach-session 
}
if which tmux 2>&1 >/dev/null; then
    test -z "$TMUX" && (tmux attach || tmux_init)
fi
