#!/bin/sh

tmux_init()
{
    tmux new-session -s work -d
    tmux rename-window -t work:1 'log'
    tmux split-window -d -p 50 -t work:1 -h
    tmux split-window -d -p 80 -t work:1.1 -v

    tmux new-window -n log -t work
    tmux split-window -d -p 40 -t work:2 -h
    tmux split-window -d -p 70 -t work:2.2 -v

    tmux send-keys -t work:1.2 "pm2 monit" C-m
    tmux send-keys -t work:1.3 "pm2 logs --timestamp" C-m 
    #tmux send-keys -t work:1.3 "NODE_ENV=development pm2 start ~/code/work/venus/app.js --name 'venus' --watch -s" C-m 
    #tmux send-keys -t work:1.3 "pm2 start ~/code/work/hogwarts/app.js --name 'hogwarts' --watch 'service' -s" C-m 
    tmux send-keys -t work:2.3 
    tmux send-keys -t work:2.2 #"pm2 logs --timestamp" C-m 
    tmux send-keys -t work:2.3 #"pm2 status" C-m 
    #tmux split-window -p 80 -t work:1 -v  
    #tmux select-window -t work:1:1
    #tmux select-pane -t work:1.1
    tmux -2 attach-session 
}
if which tmux 2>&1 >/dev/null; then
    test -z "$TMUX" && (tmux attach || tmux_init)
fi
