#!/bin/sh
tmux_init()
{
    tmux new-session -s work -d
    tmux split-window -l 100 -t work:1 -h node-inspector     
    tmux split-window -p 80 -t work:1 -v  
    tmux select-window -t work:1
    tmux select-pane -t work:1.1
    tmux -2 attach-session -d
}
if which tmux 2>&1 >/dev/null; then
    test -z "$TMUX" && (tmux attach || tmux_init)
fi
