# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh


# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="miloshadzic"

# Example aliases
alias zshconfig="vim ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Uncomment this to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment following line if you want to  shown in the command execution time stamp
# in the history command output. The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|
# yyyy-mm-dd
# HIST_STAMPS="mm/dd/yyyy"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git vundle node z zsh-syntax-highlighting zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh
# about nvm configure
#export NVM_DIR=~/.nvm
#[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
#source $(brew --prefix nvm)/nvm.sh
# User configuration
#alias tmux="tmux -2" #256 colors for tmux

export PATH=$HOME/.shell:$HOME/bin:/usr/local/bin:$PATH
# for slimerjslauncher
export SLIMERJSLAUNCHER=/Applications/Firefox.app/Contents/MacOS/firefox
export SLIMERDIR=/Users/vastwu/code/demo/slimerjs/slimerjs-lib
LANG=zh_CN.UTF-8
LC_ALL=zh_CN.UTF-8
LANGUAGE=en_US:en

bindkey -v
#unset TMUX
#tmux -2 new-session -s base
# export MANPATH="/usr/local/man:$MANPATH"

# # Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"
#. <(npm completion)
#[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


export NVM_DIR="$HOME/.nvm"
#[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
#[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion" ] && . "/usr/local/opt/nvm/etc/bash_completion"  # This loads nvm bash_completion
nvm use 12

# 内网代理
function use-proxy() {
  export {http,https,ftp,all}_proxy=http://127.0.0.1:12639
  echo $http_proxy
}
function unset-proxy() {
  unset {http,https,ftp,all}_proxy
}
function mnet() {
  ssh vastwu@pcg.mnet2.com -p 36000
}

no_proxy=.wsd.com,mirrors.tencent.com


export {http,https,ftp,all}_proxy=http://127.0.0.1:12639
#export PATH=$PATH:/Users/vastwu/.fef/bin
export PATH="$PATH:$HOME/.ft"
export W2_PORT="8082"

setopt no_nomatch
export FZF_DEFAULT_COMMAND="find . \( -name coverage -o -name docs -o -name *node_modules* -o -name .git \) -prune -o -type f -name '*'"


