# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh


# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="amuse"
ZSH_THEME="fino"

# Example aliases
alias zshconfig="vim ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Uncomment this to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment following line if you want to  shown in the command execution time stamp
# in the history command output. The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|
# yyyy-mm-dd
# HIST_STAMPS="mm/dd/yyyy"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git node z zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh
# about nvm configure
#export NVM_DIR=~/.nvm
#[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
#source $(brew --prefix nvm)/nvm.sh
# User configuration
#alias tmux="tmux -2" #256 colors for tmux

export PATH=$HOME/.shell:$HOME/bin:$HOME/.local/bin:/usr/local/bin:/opt/homebrew/bin:$PATH
# for slimerjslauncher
LANG=zh_CN.UTF-8
LC_ALL=zh_CN.UTF-8
LC_CTYPE=zh_CN.UTF-8
LANGUAGE=en_US:en

bindkey -v
#unset TMUX
#tmux -2 new-session -s base
# export MANPATH="/usr/local/man:$MANPATH"

# # Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"
#. <(npm completion)
#[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


rm -f ~/.npmrc
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
#[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

nvm use 16

# 内网代理
function use-proxy() {
  export {http,https,ftp,all}_proxy=http://127.0.0.1:12639
  echo $http_proxy
}
function unset-proxy() {
  unset {http,https,ftp,all}_proxy
}
function mnet() {
  ssh vastwu@pcg.mnet2.com -p 36000
}

# export no_proxy=${no_proxy},git.woa.com
no_proxy=.wsd.com,mirrors.tencent.com,servicewechat.com,git.woa.com,zhiyan.monitor.access.inner.woa.com,.gdt.qq.com


#export {http,https,ftp,all}_proxy=http://127.0.0.1:12639

export JAVA_HOME="/Users/vastwu/Library/java/jdk1.8.0_432.jdk/Contents/Home"
export PATH=${JAVA_HOME}/bin:$PATH
export PATH="$PATH:$HOME/.ft"
export W2_PORT="8082"
export LESSCHARSET=utf-8

setopt no_nomatch
#export FZF_DEFAULT_COMMAND="find . \( -path ./coverage -o -path ./docs -o -path ./node_modules -o -path ./.git -o -path ./dist \) -prune -o -type f -name '*'"
#export FZF_DEFAULT_COMMAND="find ./ -not -path \"*/coverage/*\" -not -path \"*/docs/*\"  -not -path \"*/.git/*\"  -not -path \"*/node_modules/*\" -not -path \"*/dist/*\" -type f -name '*'"

# 构建 find 命令
ignored_dirs=("node_modules" "dist" "docs" ".git")
exclude_conditions=()
for dir in "${ignored_dirs[@]}"; do
    exclude_conditions+=(-path \"*/$dir/*\" -prune -o)
done
# 强制忽略.git，顺便兼容多一个-o的问题
#find_command="find . \( "${exclude_conditions[@]}" -type d -name \".git\" -prune \) -o -type f -name '*'"
find_command="find . \( "${exclude_conditions[@]}" -type f -name \"core.*\" -prune \) -o -type f -print"
export FZF_DEFAULT_COMMAND=$find_command

# TSW 需要的环境变量
export LD_LIBRARY_PATH=/data/workspace/TSW/bin/tencent/api/libdcapi/x86_64/:/data/workspace/TSW/bin/tencent/api/L5/L5_sys64/:$LD_LIBRARY_PATH
#export PYTHON_PATH=/Users/vastwu/bin/python2

# 取消默认的git gf别名，改为使用工蜂cli
unalias gf


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

ulimit -S -c 0

if [[ -z "$TMUX" ]]; then
  tmux -u attach-session -t default 2>/dev/null || tmux -u new-session -s default
fi

